# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      PR_URL: ${{github.event.pull_request.html_url}}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout And Build
        run: docker compose -f compose.test.yaml up -d
      - name: front npm ci
        run: docker compose -f compose.test.yaml exec front npm ci
      - name: front build
        run: docker compose -f compose.test.yaml exec front npm run build
      - name: backend npm ci
        run: docker compose -f compose.test.yaml exec backend npm ci
      - name: backend build
        run: docker compose -f compose.test.yaml exec backend npm run build
      - name: db connection confirmation
        run: docker compose -f compose.test.yaml exec db ls
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve
      - name: Enable auto-merge for Steward PRs
        run: gh pr merge --merge --auto "$PR_URL"